export const UPDATE_CANDIDATE         = "UPDATE_CANDIDATE";
export const RECEIVE_CANDIDATE_DATA   = "RECEIVE_CANDIDATE_DATA";
export const REQUEST_CANDIDATE_ADD    = "REQUEST_CANDIDATE_ADD";
export const REQUEST_CANDIDATE_EDIT   = "REQUEST_CANDIDATE_EDIT";
export const RESET_CANDIDATE_FORM     = "RESET_CANDIDATE_FORM";
