export const UPDATE_CANDIDATE       = "UPDATE_CANDIDATE";
export const RECEIVE_CANDIDATE_DATA = "RECEIVE_CANDIDATE_DATA";
export const REQUEST_CANDIDATE_SAVE = "REQUEST_CANDIDATE_SAVE";
export const RESET_CANDIDATE_FORM   = "RESET_CANDIDATE_FORM";
