export const UPDATE_ENDORSEMENT_FORM    = 'UPDATE_ENDORSEMENT_FORM';
export const ADD_ENDORSER               = 'ADD_ENDORSER';
export const UPDATE_ENDORSER            = 'UPDATE_ENDORSER';
export const REMOVE_ENDORSER            = 'REMOVE_ENDORSER';
export const CLEAR_ENDORSEMENT_FORM     = 'CLEAR_ENDORSEMENT_FORM'
export const UPDATE_ENDORSER_TAGS       = 'UPDATE_ENDORSER_TAGS'
export const REQUEST_SAVE_ENDORSEMENT   = 'REQUEST_SAVE_ENDORSEMENT'
